#!/usr/bin/python3
"""Module that factorizes as many numbers possible to a product of
two smaller numbers(factors)"""
import math
from sys import argv


def factor_me(val):
    """Decompose to a simple integer greater than 1"""

    if val % 2 == 0:
        x = 2
        print("{}={}*{}".format(val, int(val // x), x))
    else:
        s = int(math.sqrt(val)) + 1
        for x in range(3, s, +2):
            if val % x == 0:
                print("{}={}*{}".format(val, int(val // x), x))
                return
            if val % (s + x) == 0:
                print("{}={}*{}".format(val, s + x, int(val//(s + x))))
                return
            if val % (s - x) == 0:
                print("{}={}*{}".format(val, s - x, int(val//(s - x))))
                return


def factors(filename):
    """Read file name and print"""

    with open(filename, encoding="utf-8") as file_me:
        for x in file_me.readlines():
            num = int(x)
            output = factor_me(num)


if __name__ == "__main__":
    factors(argv[1])
