#!/usr/bin/python3
from sys import argv
"""Module to factorize prime numbers"""


with open(argv[1]) as p:
    """Finds two primt factors"""
    for line in p:
        prime = int(line)
        print("{:d}=".format(prime), end='')

        if prime % 2 == 0:
            print("{}*2".format(prime//2))
            continue

        for x in range(3, prime, 2):
            if prime % x == 0:
                factor = prime//x

                for y in range(3, factor, 2):
                    if factor % y == 0 or y == 0:
                        break
                    print("{}*{}".format(factor, x))
                    break
